### ISSUE TITLE
Update .spec file to depend on sqlite >= 3.8.9

### ISSUE THREAD

**Issue by siteshwar** [nemomobile-packages/gecko-dev#59]
Gecko38 depends on sqlite >= 3.8.9. Spec file should be updated to reflect this dependency.

**Comment by rainemak** [comment]
This repo obsolete. See https://git.merproject.org/mer-core/gecko-dev

Not necessary to specify in spec file as the configuration does the check. From documentation point of view, could be added to the spec as well. See more info from https://git.merproject.org/mer-core/gecko-dev/merge_requests/5

**Comment by siteshwar** [comment]
The check you are mentioning is only done at compile time. This dependency should be mentioned as runtime dependency too in .spec file.

I am aware about the switch to https://git.merproject.org/mer-core/gecko-dev but thought we still would like to use GitHub for tracking issues. What would be the ideal way to track issues after switching to https://git.merproject.org/mer-core/gecko-dev ?

**Comment by siteshwar** [comment]
Opened PR at https://git.merproject.org/mer-core/gecko-dev/merge_requests/16

**Comment by siteshwar** [comment]
Closing this issue as PR is merged now.

We now have all nemomobile related components listed under Mer Core project at https://bugs.merproject.org/, so in future we should use Mer bugzilla for tracking issues.
